"""initial schema

Revision ID: 2429f8c9ce7a
Revises:
Create Date: 2026-09-28 19:46:17.936136

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2429f8c9ce7a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "phase",
            sa.Enum(
                "idle", "topic_set", "assessing", "scoring", "explaining", "follow_up", name="phase"
            ),
            nullable=False,
        ),
        sa.Column("iq_score", sa.Integer(), nullable=True),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_topics_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
    )
    op.create_index(
        "ix_topics_user_id_updated_at",
        "topics",
        ["user_id", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("iq_score", sa.Integer(), nullable=True),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column(
            "status", sa.Enum("in_progress", "completed", name="assessment_status"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "correct_count >= 0 AND correct_count <= 3",
            name=op.f("ck_assessments_correct_count_range"),
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_assessments_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
        sa.UniqueConstraint("topic_id", name=op.f("uq_assessments_topic_id")),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "assistant", "system", name="message_role"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "phase",
            sa.Enum(
                "idle", "topic_set", "assessing", "scoring", "explaining", "follow_up", name="phase"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_messages_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_topic_id_created_at",
        "messages",
        ["topic_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "assessment_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", name="question_difficulty"),
            nullable=False,
        ),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correct_option", sa.String(length=1), nullable=False),
        sa.Column("chosen_option", sa.String(length=1), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "chosen_option IS NULL OR chosen_option IN ('A', 'B', 'C', 'D')",
            name=op.f("ck_assessment_questions_chosen_option_letter"),
        ),
        sa.CheckConstraint(
            "correct_option IN ('A', 'B', 'C', 'D')",
            name=op.f("ck_assessment_questions_correct_option_letter"),
        ),
        sa.CheckConstraint(
            "options ? 'A' AND options ? 'B' AND options ? 'C' AND options ? 'D'",
            name=op.f("ck_assessment_questions_option_keys"),
        ),
        sa.CheckConstraint(
            "(chosen_option IS NULL) = (answered_at IS NULL)",
            name=op.f("ck_assessment_questions_answered_pairing"),
        ),
        sa.CheckConstraint(
            "ordinal >= 1 AND ordinal <= 3", name=op.f("ck_assessment_questions_ordinal_range")
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_assessment_questions_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_questions")),
        sa.UniqueConstraint(
            "assessment_id", "ordinal", name=op.f("uq_assessment_questions_assessment_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assessment_questions")
    op.drop_index("ix_messages_topic_id_created_at", table_name="messages")
    op.drop_table("messages")
    op.drop_table("assessments")
    op.drop_index("ix_topics_user_id_updated_at", table_name="topics")
    op.drop_table("topics")
    op.drop_table("users")
    # ### end Alembic commands ###
